const {chromium} = require('playwright');
const fs = require('node:fs');
const assert = require('node:assert/strict');
(async()=>{
  const browser = await chromium.connectOverCDP('http://127.0.0.1:9224');
  const page=browser.contexts()[0].pages()[0];
  const errors=[]; const consoleErrors=[];
  page.on('pageerror',e=>errors.push(e.message)); page.on('console',m=>{if(m.type()==='error')consoleErrors.push(m.text())});
  if (page.url() === 'about:blank') await page.goto('http://tauri.localhost/'); else await page.reload();
  await page.getByRole('button',{name:'打开菜单',exact:true}).waitFor({timeout:30000});
  await page.keyboard.press('Escape');
  await page.getByRole('navigation',{name:'主导航'}).waitFor({timeout:30000});
  assert(!page.url().includes(':1430'));
  await page.getByRole('navigation').getByRole('button',{name:'设置',exact:true}).click();
  await page.getByRole('button',{name:'启动本地演示',exact:true}).click();
  await page.getByRole('navigation').getByRole('button',{name:'指挥台',exact:true}).click();
  await page.waitForFunction(()=>document.querySelector('.health-value')?.textContent?.includes('380'),null,{timeout:15000});
  await page.keyboard.press('Escape');
  await page.screenshot({path:'artifacts/release-demo.png',fullPage:true});
  await page.keyboard.press('Escape');
  await page.getByRole('navigation').getByRole('button',{name:'设置',exact:true}).click();
  await page.getByRole('button',{name:'断开连接',exact:true}).click();
  await page.getByLabel('MQTT 主机',{exact:true}).fill('127.0.0.1');
  await page.getByLabel('MQTT 端口',{exact:true}).fill('1884');
  await page.getByLabel('发送端 IP 过滤',{exact:true}).fill('127.0.0.1');
  await page.getByLabel('本地监听端口',{exact:true}).fill('3335');
  await page.getByRole('button',{name:'连接裁判系统',exact:true}).click();
  await page.getByText('本机测试链路 · 实时',{exact:true}).waitFor({timeout:20000});
  await page.getByRole('navigation').getByRole('button',{name:'指挥台',exact:true}).click();
  await page.keyboard.press('Escape');
  await page.getByRole('button',{name:'启动视频接收',exact:true}).click();
  await page.waitForFunction(()=>document.querySelector('.live-video')?.naturalWidth>0,null,{timeout:20000});
  await page.waitForTimeout(2000);
  await page.screenshot({path:'artifacts/release-mqtt-video.png',fullPage:true});
  await page.getByRole('button',{name:'启用控制',exact:true}).click();
  await page.locator('.capture-layer').waitFor({timeout:5000});
  await page.keyboard.press('Escape');
  await page.getByRole('dialog',{name:'操作菜单'}).waitFor();
  assert.equal(await page.locator('.capture-layer').count(),0);
  const before=await page.evaluate(async()=>(await window.api.udpStream.getStatus()).stats.decodedFrames);
  await page.waitForTimeout(700);
  const after=await page.evaluate(async()=>(await window.api.udpStream.getStatus()).stats.decodedFrames);
  assert(after > before);
  await page.keyboard.press('Escape');
  assert.equal(await page.locator('.capture-layer').count(),0);
  assert(await page.getByRole('button',{name:'启用控制',exact:true}).isVisible());
  const stats=await page.evaluate(async()=>({mqtt:await window.api.mqtt.getStats(),udp:await window.api.udpStream.getStatus()}));
  await page.keyboard.press('Escape');
  await page.getByRole('navigation').getByRole('button',{name:'设置',exact:true}).click();
  await page.getByRole('button',{name:'停止视频',exact:true}).click();
  await page.getByRole('button',{name:'断开连接',exact:true}).click();
  await page.getByRole('button',{name:'启动本地演示',exact:true}).click();
  await page.getByRole('navigation').getByRole('button',{name:'指挥台',exact:true}).click();
  await page.keyboard.press('Escape');
  fs.writeFileSync('artifacts/release-check.json',JSON.stringify({checkedAt:new Date().toISOString(),url:page.url(),errors,consoleErrors,escReleasesControl:true,videoContinuesBehindMenu:true,stats},null,2));
  assert.deepEqual(errors,[]);assert.deepEqual(consoleErrors,[]);
  console.log(JSON.stringify({url:page.url(),errors,consoleErrors,decodedFrames:stats.udp.stats.decodedFrames},null,2));
  await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
